In [1]:
import os
import glob

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="darkgrid")

# ============================================================
# LOAD RESULTS
# ============================================================

RESULTS_PATH = "./results/exploratory_analysis_500"

files = glob.glob(os.path.join(RESULTS_PATH, "meeting*.csv"))

print("Loaded files:")
for f in files:
    print(os.path.basename(f))

dfs = []

for file in files:
    df_tmp = pd.read_csv(file)

    # source filename
    df_tmp["source_file"] = os.path.basename(file)

    dfs.append(df_tmp)

df_meeting = pd.concat(dfs, ignore_index=True)

df_meeting = df_meeting[df_meeting["number_of_islands"]==500]

print(f"\nTotal rows: {len(df_meeting)}")

display(df_meeting.head())

print("\nColumns:")
print(df_meeting.columns.tolist())

Loaded files:
meeting-200-5.csv
meeting-300-5.csv
meeting-100-5.csv
meeting-50-5.csv
meeting-500-5.csv
meeting_n500_array_20412467.csv
meeting-300-5_2.csv
meeting-500-5_2.csv

Total rows: 98

,array_task_id,topology,number_of_islands,number_of_migrants,migration_interval,z_star,n_steps,r0,r1,gamma,build_target_ratio,average,best,source_file,seed
78,54,meeting,500,5,5,5,1000,0.00025,1.0,0.0005,0.8,141.266002,87.771233,meeting-500-5.csv,NaN
79,55,meeting,500,5,5,5,1000,0.00025,1.0,0.0010,0.8,126.500743,74.016666,meeting-500-5.csv,NaN
80,56,meeting,500,5,5,5,1000,0.00025,1.0,0.0050,0.8,158.256175,89.568856,meeting-500-5.csv,NaN
81,57,meeting,500,5,5,5,1000,0.00025,2.0,0.0005,0.8,130.987897,81.612486,meeting-500-5.csv,NaN
82,58,meeting,500,5,5,5,1000,0.00025,2.0,0.0010,0.8,128.670671,75.501846,meeting-500-5.csv,NaN

Columns:
['array_task_id', 'topology', 'number_of_islands', 'number_of_migrants', 'migration_interval', 'z_star', 'n_steps', 'r0', 'r1', 'gamma', 'build_target_ratio', 'average', 'best', 'source_file', 'seed']

In [2]:
top10 = df_meeting.sort_values("best").head(10)

top10[["best", "average", "number_of_islands", "z_star", "n_steps", "r0", "r1", "gamma", "source_file"]]

,best,average,number_of_islands,z_star,n_steps,r0,r1,gamma,source_file
138,38.989876,81.874847,500,15,1000,0.0020,1.0,0.010,meeting_n500_array_20412467.csv
139,39.759903,83.493152,500,15,1000,0.0020,1.0,0.005,meeting_n500_array_20412467.csv
116,40.757107,74.559198,500,10,1000,0.0005,1.0,0.005,meeting-500-5.csv
164,41.181233,76.892176,500,20,2000,0.0010,1.0,0.020,meeting_n500_array_20412467.csv
125,41.976226,85.165508,500,10,1000,0.0010,1.0,0.005,meeting-500-5.csv
161,43.425561,69.340975,500,20,2000,0.0005,1.0,0.020,meeting_n500_array_20412467.csv
155,43.739746,71.834988,500,20,1000,0.0010,1.0,0.020,meeting_n500_array_20412467.csv
166,43.946922,76.028272,500,20,2000,0.0020,1.0,0.010,meeting_n500_array_20412467.csv
142,44.324464,74.982247,500,15,2000,0.0005,1.0,0.005,meeting_n500_array_20412467.csv
162,44.783061,73.559996,500,20,2000,0.0010,1.0,0.005,meeting_n500_array_20412467.csv

In [10]:
top5 = df_meeting.sort_values("best").head(5)

param_cols = top5.columns[2:10] # ignoruje pierwsze 2 i ostatnie 4 kolumny
#top3 = top3_per_islands[top3_per_islands['number_of_islands']!=500]

out = top5[param_cols].copy()

# Dla częsci wcześniejszych eksperymentów nie było zapisu tych parametrów, więc dodałem je ręcznie. W nowszej wersji zapisują się automatycznie
out["build_target_ratio"] = 0.8
out["seed"] = 123

# powtarzamy każdą konfigurację parametrów 5-krotnie
out_repeated = out.loc[out.index.repeat(5)].reset_index(drop=True)

out_repeated.to_csv(
    "top5_meeting_500.txt",
    sep=" ",
    header=False,
    index=False
)

In [3]:
files2 = glob.glob(os.path.join(RESULTS_PATH, "scale_free*.csv"))

print("Loaded files:")
for f in files2:
    print(os.path.basename(f))

dfs = []

for file in files2:
    df_tmp = pd.read_csv(file)

    # source filename
    df_tmp["source_file"] = os.path.basename(file)

    dfs.append(df_tmp)

df_scale_free = pd.concat(dfs, ignore_index=True)

df_scale_free = df_scale_free[df_scale_free["number_of_islands"]==500]

print(f"\nTotal rows: {len(df_scale_free)}")

display(df_scale_free.head())

print("\nColumns:")
print(df_scale_free.columns.tolist())

Loaded files:
scale_free_n500_array_20089410.csv
scale_free-500-5.csv
scale_free_n500_array_20406088.csv
scale_free_n500_array_20486504.csv
scale_free_n50_array_20259859.csv
scale_free_n300_array_20259859.csv
scale_free_n100_array_20089410.csv
scale_free_n100_array_20256742.csv
scale_free_n200_array_20259859.csv
scale_free_n500_array_20258306.csv
scale_free_n200_array_20256742.csv
scale_free_n100_array_20259859.csv
scale_free_n200_array_20089410.csv
scale_free-300-5.csv
scale_free_n500_array_20259859.csv
scale_free_n500_array_20486278.csv
scale_free_n300_array_20256742.csv
scale_free_n50_array_20256742.csv
scale_free_n50_array_20089410.csv
scale_free_n300_array_20089410.csv

Total rows: 171

,array_task_id,topology,number_of_islands,number_of_migrants,migration_interval,m0,m,seed,average,best,source_file,build_target_ratio
0,65,scale_free,500,5,5,3,2,123.0,802.280096,140.086448,scale_free_n500_array_20089410.csv,NaN
1,66,scale_free,500,5,5,3,3,123.0,357.705721,94.833971,scale_free_n500_array_20089410.csv,NaN
2,69,scale_free,500,5,5,5,3,123.0,374.688380,71.344838,scale_free_n500_array_20089410.csv,NaN
3,70,scale_free,500,5,5,5,4,123.0,323.786031,70.063920,scale_free_n500_array_20089410.csv,NaN
4,64,scale_free,500,5,5,3,1,123.0,803.087625,146.289448,scale_free_n500_array_20089410.csv,NaN

Columns:
['array_task_id', 'topology', 'number_of_islands', 'number_of_migrants', 'migration_interval', 'm0', 'm', 'seed', 'average', 'best', 'source_file', 'build_target_ratio']

In [4]:
top10 = df_scale_free.sort_values("best").head(20)

top10[["best", "average", "number_of_islands", "m0", "m","source_file", "array_task_id"]]

,best,average,number_of_islands,m0,m,source_file,array_task_id
65,20.440770,71.405154,500,60,59,scale_free_n500_array_20486504.csv,8
34,20.801061,81.497615,500,35,31,scale_free_n500_array_20406088.csv,10
362,22.399735,75.661146,500,50,43,scale_free_n500_array_20486278.csv,27
28,22.570059,73.045590,500,25,25,scale_free_n500_array_20406088.csv,4
29,22.794668,73.254678,500,30,26,scale_free_n500_array_20406088.csv,5
72,23.524543,81.937989,500,80,80,scale_free_n500_array_20486504.csv,19
71,23.524543,81.929656,500,80,78,scale_free_n500_array_20486504.csv,17
76,23.746049,70.294033,500,100,94,scale_free_n500_array_20486504.csv,23
73,23.798259,83.536062,500,80,79,scale_free_n500_array_20486504.csv,18
77,24.115351,77.877554,500,100,92,scale_free_n500_array_20486504.csv,21
49,24.330796,82.643352,500,50,46,scale_free_n500_array_20406088.csv,25
358,24.371166,85.676041,500,45,39,scale_free_n500_array_20486278.csv,23
43,24.406362,80.505651,500,40,40,scale_free_n500_array_20406088.csv,19
354,24.524913,84.960116,500,40,35,scale_free_n500_array_20486278.csv,19
355,24.584424,90.733344,500,45,36,scale_free_n500_array_20486278.csv,20
50,24.620355,87.473547,500,50,47,scale_free_n500_array_20406088.csv,26
68,24.885606,82.312628,500,80,75,scale_free_n500_array_20486504.csv,14
351,25.055083,99.702443,500,40,32,scale_free_n500_array_20486278.csv,16
74,25.213992,78.972846,500,100,91,scale_free_n500_array_20486504.csv,20
35,25.531924,85.688250,500,35,32,scale_free_n500_array_20406088.csv,11

In [5]:
df_m0 = (
    df_scale_free.groupby("m0", as_index=False)
    .agg({
        "best": ["mean", "min", "max", "std"],
        "average": ["mean", "min", "max", "std"],
    })
)

# spłaszczenie nazw kolumn
df_m0.columns = [
    "_".join(col).strip("_")
    for col in df_m0.columns.values
]

df_m0

,m0,best_mean,best_min,best_max,best_std,average_mean,average_min,average_max,average_std
0,3,121.726807,92.122609,146.289448,22.993025,622.709551,319.835830,803.087625,222.871724
1,5,96.788095,56.588856,303.795157,74.067601,374.840825,153.541540,1149.722996,284.025375
2,8,61.217808,39.527732,86.040352,19.145261,252.608456,130.334723,383.426864,122.060855
3,10,40.300698,33.668706,44.292556,3.421213,224.043138,172.584034,426.517907,100.763140
4,12,38.926798,33.668706,55.352197,6.899969,222.020936,89.929764,473.034101,152.751084
5,15,64.364351,27.172644,240.081786,59.331137,252.469492,80.311423,1533.954249,381.088531
6,20,47.687997,26.702462,130.690038,30.421000,201.467592,65.058205,999.864218,275.374202
7,25,30.905789,22.570059,53.464738,8.874035,94.516585,73.045590,115.889160,12.957335
8,30,30.861379,22.794668,40.906764,4.644886,99.540315,73.254678,126.849739,16.952082
9,35,31.934148,20.801061,42.617659,6.326709,104.826327,81.497615,119.803439,13.700976
10,40,28.792342,24.406362,36.888110,4.348173,95.192975,80.505651,108.693819,9.516258
11,45,30.172159,24.371166,40.241176,5.305380,96.361797,85.676041,117.338302,12.009504
12,50,28.733698,22.399735,37.051781,4.681616,91.742043,75.661146,107.364694,9.713094
13,60,28.531712,20.440770,34.740983,4.157065,78.814411,65.285354,103.197237,14.051992
14,80,28.140955,23.524543,40.855008,5.445532,85.957353,65.929883,120.351235,14.526399
15,100,28.582205,23.746049,38.831565,4.695526,82.730121,70.294033,100.350705,8.493919

In [6]:
df_scale_free["m_gap"] = (
    df_scale_free["m0"] - df_scale_free["m"]
)

df_gap = (
    df_scale_free.groupby("m_gap", as_index=False)
    .agg({
        "best": ["mean", "min", "max", "std"],
        "average": ["mean", "min", "max", "std"],
    })
)

df_gap.columns = [
    "_".join(col).strip("_")
    for col in df_gap.columns.values
]

df_gap

,m_gap,best_mean,best_min,best_max,best_std,average_mean,average_min,average_max,average_std
0,0,40.805831,22.570059,94.833971,21.919016,148.893292,66.008849,403.246251,104.591063
1,1,45.184094,20.440770,140.086448,34.578583,201.889419,65.058205,802.280096,225.740405
2,2,49.448326,23.524543,146.289448,37.276233,203.400992,65.146290,803.087625,223.676380
3,3,38.666986,24.620355,97.339506,19.876593,129.012553,65.582048,364.609641,86.892971
4,4,51.396001,20.801061,303.795157,68.843374,187.890428,73.254678,1149.722996,267.774969
5,5,37.821541,24.524913,81.402714,15.386123,131.731822,79.610683,383.037096,77.520177
6,6,39.163074,23.746049,86.040352,15.948818,129.383959,65.387451,383.426864,78.931820
7,7,37.342389,22.399735,81.402714,14.592256,131.674174,65.285354,383.339235,79.237241
8,8,31.941563,24.115351,43.482251,5.860546,126.166435,65.929883,402.591424,87.018967
9,9,32.629639,24.584424,48.615050,6.838874,123.839295,65.483437,401.840182,87.558035
10,10,40.423001,34.927613,50.560523,8.789711,227.309957,86.816158,473.034101,213.532536
11,11,49.433335,33.668706,76.907077,23.879210,236.392828,87.157176,418.665824,168.205516
12,12,58.392714,39.589233,77.196195,26.592138,168.446044,133.531533,203.360556,49.376576
13,13,105.223946,49.664033,160.783858,78.573582,392.939497,137.636944,648.242051,361.052334
14,14,147.869757,55.657729,240.081786,130.407502,839.868201,145.782152,1533.954249,981.585903
15,15,54.776543,54.776543,54.776543,NaN,178.504677,178.504677,178.504677,NaN
16,16,55.483033,55.483033,55.483033,NaN,177.877208,177.877208,177.877208,NaN
17,17,60.800391,60.800391,60.800391,NaN,179.061119,179.061119,179.061119,NaN
18,18,130.690038,130.690038,130.690038,NaN,999.618039,999.618039,999.618039,NaN
19,19,130.690038,130.690038,130.690038,NaN,999.864218,999.864218,999.864218,NaN

In [7]:
df_scale_free["m_ratio"] = (
    df_scale_free["m"] / df_scale_free["m0"]
)

bins = [0, 0.2, 0.4, 0.6, 0.8, 1.0]

df_scale_free["m_ratio_bin"] = pd.cut(
    df_scale_free["m_ratio"],
    bins=bins,
    include_lowest=True
)

df_ratio = (
    df_scale_free.groupby("m_ratio_bin", as_index=False)
    .agg({
        "best": ["mean", "min", "max", "std"],
        "average": ["mean", "min", "max", "std"],
    })
)

df_ratio

/var/folders/y3/yq4_6mjd0vxdjk2jv9k082q00000gn/T/ipykernel_3412/3427861800.py:14: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_scale_free.groupby("m_ratio_bin", as_index=False)

     m_ratio_bin        best                                       average  \
                        mean        min         max        std        mean
0  (-0.001, 0.2]  104.757970  33.668706  303.795157  81.797162  559.409653
1     (0.2, 0.4]   67.292981  33.668706  146.289448  32.985562  304.146232
2     (0.4, 0.6]   48.549961  31.296843   97.339506  17.180810  173.647148
3     (0.6, 0.8]   42.643008  24.584424  140.086448  25.964402  161.415270
4     (0.8, 1.0]   31.617892  20.440770   94.833971  11.321140  104.851746


          min          max         std
0  174.369285  1533.954249  440.694518
1  113.539661   803.087625  205.085676
2   86.772561   374.688380   96.957050
3   87.928028   802.280096  164.363203
4   65.058205   426.517907   62.439114

In [8]:
df_scale_free["m_gap"] = (
    df_scale_free["m0"] - df_scale_free["m"]
)

bins = [-1, 2, 5, 10, 20, 100]

labels = [
    "0-2",
    "3-5",
    "6-10",
    "11-20",
    ">20"
]

df_scale_free["m_gap_bin"] = pd.cut(
    df_scale_free["m_gap"],
    bins=bins,
    labels=labels
)

df_gap_bin = (
    df_scale_free.groupby("m_gap_bin", as_index=False)
    .agg({
        "best": ["mean", "min", "max", "std"],
        "average": ["mean", "min", "max", "std"],
    })
)

df_gap_bin

/var/folders/y3/yq4_6mjd0vxdjk2jv9k082q00000gn/T/ipykernel_3412/3321334789.py:22: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_scale_free.groupby("m_gap_bin", as_index=False)

  m_gap_bin       best                                       average  \
                  mean        min         max        std        mean
0       0-2  45.146084  20.440770  146.289448  31.559510  184.727901
1       3-5  42.837160  20.801061  303.795157  42.660770  150.319418
2      6-10  35.645107  22.399735   86.040352  11.787855  133.102074
3     11-20  85.979492  33.668706  240.081786  59.156665  431.900802
4       >20        NaN        NaN         NaN        NaN         NaN


         min          max         std
0  65.058205   803.087625  191.197183
1  65.582048  1149.722996  170.072876
2  65.285354   473.034101   91.149313
3  87.157176  1533.954249  445.476615
4        NaN          NaN         NaN

In [9]:
top5 = df_scale_free.sort_values("best").head(5)

param_cols = top5.columns[2:7] # ignoruje pierwsze 2 i ostatnie 5 kolumn
#top10 = top10_per_islands[top10_per_islands['number_of_islands']==500]

out = top5[param_cols].copy()
out["seed"] = 123

out_scale_free = out.loc[out.index.repeat(5)].reset_index(drop=True)

out_scale_free.to_csv(
    "top5_scale_500.txt",
    sep=" ",
    header=False,
    index=False
)

In [13]:
out_scale_free

    number_of_islands  number_of_migrants  migration_interval  m0   m  seed
0                 500                   5                   5  60  59   123
1                 500                   5                   5  60  59   123
2                 500                   5                   5  60  59   123
3                 500                   5                   5  60  59   123
4                 500                   5                   5  60  59   123
5                 500                   5                   5  35  31   123
6                 500                   5                   5  35  31   123
7                 500                   5                   5  35  31   123
8                 500                   5                   5  35  31   123
9                 500                   5                   5  35  31   123
10                500                   5                   5  50  43   123
11                500                   5                   5  50  43   123
12                500                   5                   5  50  43   123
13                500                   5                   5  50  43   123
14                500                   5                   5  50  43   123
15                500                   5                   5  25  25   123
16                500                   5                   5  25  25   123
17                500                   5                   5  25  25   123
18                500                   5                   5  25  25   123
19                500                   5                   5  25  25   123
20                500                   5                   5  30  26   123
21                500                   5                   5  30  26   123
22                500                   5                   5  30  26   123
23                500                   5                   5  30  26   123
24                500                   5                   5  30  26   123